"""Operational processes: privacy, security, third party, resilience, people,
change, and the governance of the organisation's own AI.

The privacy processes carry statutory clocks, so their gates are marked
``statutory`` and their SLAs are expressed in hours rather than days. A missed
Article 33 deadline is not a process failure that can be corrected later.
"""

from __future__ import annotations

from app.processes import Activity, Automation, Cadence, Process

# ==========================================================================
# PRV — Privacy operations
# ==========================================================================
PRIVACY: tuple[Process, ...] = (
    Process(
        code="PR-PRV-01",
        name="Records of processing and lawful basis",
        domain="PRV",
        purpose=(
            "Maintains the Article 30 record and the lawful basis behind every "
            "processing activity. Everything else in privacy depends on knowing "
            "what is processed, why, and on what basis."
        ),
        owner_role="DPO",
        trigger="New or changed processing; annual attestation",
        cadence=Cadence.ANNUAL,
        clauses={
            "uk_gdpr": ("Art.5", "Art.6", "Art.9", "Art.30"),
            "iso27001": ("A.5.34", "A.8.11"),
        },
        outputs=("processing_record", "lawful_basis_determination"),
        kpis=("Records attested within 12 months", "Records with documented lawful basis"),
        activities=(
            Activity(
                code="A1",
                what="Capture the processing activity: purpose, categories, subjects, recipients, transfers, retention.",
                responsible="agent",
                accountable="DPO",
                trigger="New processing declared, or discovery from system inventory",
                inputs=("intake_form", "asset_register", "supplier_register"),
                outputs=("draft_processing_record",),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role="Draft the record from what was declared and flag any field left unstated.",
                task_class="classification",
                control_refs=("uk_gdpr:Art.30",),
            ),
            Activity(
                code="A2",
                what="Determine the lawful basis, and the additional condition where special category data is involved.",
                responsible="DPO",
                accountable="DPO",
                inputs=("draft_processing_record",),
                outputs=("lawful_basis_determination",),
                automation=Automation.MANUAL,
                control_refs=("uk_gdpr:Art.6", "uk_gdpr:Art.9"),
                evidence=("lawful_basis_record",),
            ),
            Activity(
                code="A3",
                what="Screen for the need for an impact assessment.",
                responsible="agent",
                accountable="DPO",
                inputs=("draft_processing_record", "lawful_basis_determination"),
                outputs=("dpia_screening",),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role=(
                    "Apply the high-risk criteria and say whether an assessment "
                    "is required, likely required, or not required, with reasons."
                ),
                task_class="classification",
                min_confidence=0.85,
                control_refs=("uk_gdpr:Art.35",),
            ),
            Activity(
                code="A4",
                what="Approve the record for the Article 30 register.",
                responsible="DPO",
                accountable="DPO",
                inputs=("draft_processing_record", "lawful_basis_determination"),
                outputs=("processing_record",),
                automation=Automation.GATE,
                gate_type="privacy.lawful_basis",
                gate_reason="statutory",
                control_refs=("uk_gdpr:Art.30",),
                evidence=("processing_record_approval",),
            ),
            Activity(
                code="A5",
                what="Re-attest the record annually and detect drift from the systems it describes.",
                responsible="agent",
                accountable="DPO",
                trigger="Annual, or on detected change",
                inputs=("processing_record", "system_inventory"),
                outputs=("attestation_request", "drift_findings"),
                automation=Automation.AUTO_NOTIFY,
                agent="privacy",
                ai_role="Compare the record against current system reality and report differences.",
                task_class="control_assessment",
                control_refs=("uk_gdpr:Art.30",),
            ),
        ),
    ),
    Process(
        code="PR-PRV-02",
        name="Data subject rights request",
        domain="PRV",
        purpose=(
            "Handles an individual exercising their rights, within the statutory "
            "period, without disclosing anyone else's data in the process."
        ),
        owner_role="DPO",
        trigger="Request received through any channel",
        cadence=Cadence.EVENT,
        clauses={
            "uk_gdpr": ("Art.12", "Art.15", "Art.16", "Art.17", "Art.18", "Art.20", "Art.21"),
            "iso27001": ("A.5.34",),
        },
        outputs=("dsar_record", "response_pack", "release_record"),
        kpis=("Responses within the statutory period", "Requests where identity verification stalled"),
        notes=(
            "Release is a gate for a specific reason: a subject access response "
            "usually contains third-party personal data, and disclosing it is an "
            "irreversible breach of someone else's rights."
        ),
        activities=(
            Activity(
                code="A1",
                what="Log the request, classify its type and start the statutory clock from receipt.",
                responsible="agent",
                accountable="DPO",
                trigger="Request received",
                inputs=("request",),
                outputs=("dsar_record", "statutory_deadline"),
                automation=Automation.AUTO,
                agent="privacy",
                ai_role="Classify the right being exercised and compute the deadline.",
                task_class="classification",
                min_confidence=0.85,
                control_refs=("uk_gdpr:Art.12",),
                sla_hours=24,
            ),
            Activity(
                code="A2",
                what="Verify the requester's identity proportionately to the data at stake.",
                responsible="Operator",
                accountable="DPO",
                inputs=("dsar_record",),
                outputs=("identity_verification",),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role="Check the evidence supplied against the verification standard and say what is missing.",
                task_class="classification",
                control_refs=("uk_gdpr:Art.12",),
                sla_hours=72,
            ),
            Activity(
                code="A3",
                what="Search the estate for the subject's data across every system in the Article 30 register.",
                responsible="agent",
                accountable="DPO",
                inputs=("identity_verification", "processing_records", "system_connectors"),
                outputs=("search_results",),
                automation=Automation.AUTO,
                agent="privacy",
                ai_role=None,
                control_refs=("uk_gdpr:Art.15",),
                evidence=("dsar_search_record",),
            ),
            Activity(
                code="A4",
                what="Assemble the response pack and mark third-party data and exemptions for redaction.",
                responsible="agent",
                accountable="DPO",
                inputs=("search_results",),
                outputs=("draft_response_pack", "redaction_proposals"),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role=(
                    "Assemble the pack and identify every item containing another "
                    "person's data or falling under an exemption. Over-inclusion "
                    "here is a breach; flag anything uncertain for review."
                ),
                task_class="evidence_summary",
                min_confidence=0.9,
                control_refs=("uk_gdpr:Art.15",),
            ),
            Activity(
                code="A5",
                what="Review redactions and confirm the pack discloses nothing it should not.",
                responsible="DPO",
                accountable="DPO",
                inputs=("draft_response_pack", "redaction_proposals"),
                outputs=("reviewed_pack",),
                automation=Automation.MANUAL,
                control_refs=("uk_gdpr:Art.15",),
            ),
            Activity(
                code="A6",
                what="Release the response to the data subject.",
                responsible="DPO",
                accountable="DPO",
                inputs=("reviewed_pack",),
                outputs=("release_record",),
                automation=Automation.GATE,
                gate_type="privacy.dsar_release",
                gate_reason="irreversible",
                control_refs=("uk_gdpr:Art.12", "uk_gdpr:Art.15"),
                evidence=("dsar_release_record",),
            ),
        ),
    ),
    Process(
        code="PR-PRV-03",
        name="Personal data breach assessment and notification",
        domain="PRV",
        purpose=(
            "Runs the 72-hour clock from awareness. The deadline runs from the "
            "moment the organisation knows, which is why the clock starts when "
            "the incident is recorded rather than when someone opens a breach file."
        ),
        owner_role="DPO",
        trigger="Incident involving personal data",
        cadence=Cadence.EVENT,
        clauses={
            "uk_gdpr": ("Art.33", "Art.34", "Art.5"),
            "iso27001": ("A.5.24", "A.5.26", "A.6.8"),
        },
        outputs=("breach_record", "risk_to_individuals", "notification_decision"),
        kpis=("Notifications within 72 hours", "Time from detection to breach determination"),
        autonomy_tier="L2",
        activities=(
            Activity(
                code="A1",
                what="Determine whether the incident is a personal data breach and start the clock.",
                responsible="agent",
                accountable="DPO",
                trigger="Incident recorded with personal data involvement",
                inputs=("incident",),
                outputs=("breach_determination", "clock_start"),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role=(
                    "Assess against the breach definition and cite the basis. If "
                    "it is genuinely unclear, treat it as a breach and say why — "
                    "the clock is running either way."
                ),
                task_class="classification",
                min_confidence=0.85,
                control_refs=("uk_gdpr:Art.33",),
                sla_hours=4,
            ),
            Activity(
                code="A2",
                what="Establish the facts: categories, approximate numbers, cause, containment.",
                responsible="agent",
                accountable="DPO",
                inputs=("breach_determination", "incident_evidence"),
                outputs=("breach_facts",),
                automation=Automation.ASSIST,
                agent="incident",
                ai_role="Assemble what is known and state plainly what is not yet known.",
                task_class="evidence_summary",
                control_refs=("uk_gdpr:Art.33",),
                sla_hours=12,
            ),
            Activity(
                code="A3",
                what="Assess the risk to the rights and freedoms of the individuals affected.",
                responsible="DPO",
                accountable="DPO",
                inputs=("breach_facts",),
                outputs=("risk_to_individuals",),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role="Draft the assessment with the factors driving it; the DPO reaches the conclusion.",
                task_class="dpia_drafting",
                min_confidence=0.85,
                control_refs=("uk_gdpr:Art.33", "uk_gdpr:Art.34"),
                sla_hours=24,
            ),
            Activity(
                code="A4",
                what="Decide whether to notify the supervisory authority.",
                responsible="DPO",
                accountable="DPO",
                inputs=("risk_to_individuals",),
                outputs=("notification_decision",),
                automation=Automation.GATE,
                gate_type="privacy.breach_notify",
                gate_reason="statutory",
                control_refs=("uk_gdpr:Art.33",),
                evidence=("breach_notification_decision",),
                sla_hours=72,
            ),
            Activity(
                code="A5",
                what="Decide whether the individuals themselves must be told.",
                responsible="DPO",
                accountable="DPO",
                inputs=("risk_to_individuals", "notification_decision"),
                outputs=("subject_notification_decision",),
                automation=Automation.GATE,
                gate_type="privacy.subject_notification",
                gate_reason="irreversible",
                control_refs=("uk_gdpr:Art.34",),
            ),
            Activity(
                code="A6",
                what="Record the decision, the reasoning and any submission reference.",
                responsible="agent",
                accountable="DPO",
                inputs=("notification_decision", "subject_notification_decision"),
                outputs=("breach_record",),
                automation=Automation.AUTO,
                agent="evidence",
                control_refs=("uk_gdpr:Art.33.5",),
                evidence=("breach_register_entry",),
            ),
        ),
    ),
    Process(
        code="PR-PRV-04",
        name="Data protection impact assessment",
        domain="PRV",
        purpose=(
            "Assesses high-risk processing before it starts, and determines "
            "whether the regulator must be consulted."
        ),
        owner_role="DPO",
        trigger="Screening indicates high risk; new technology or large-scale processing",
        cadence=Cadence.EVENT,
        clauses={
            "uk_gdpr": ("Art.35", "Art.36", "Art.25"),
            "iso27001": ("A.8.25", "A.8.27"),
        },
        outputs=("dpia_report", "residual_risk_position", "consultation_decision"),
        kpis=("DPIAs completed before processing begins", "Consultations required and made"),
        activities=(
            Activity(
                code="A1",
                what="Describe the processing, its necessity and its proportionality.",
                responsible="agent",
                accountable="DPO",
                inputs=("processing_record", "system_design"),
                outputs=("processing_description",),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role="Draft the description and test the necessity argument against the stated purpose.",
                task_class="dpia_drafting",
                control_refs=("uk_gdpr:Art.35.7",),
            ),
            Activity(
                code="A2",
                what="Assess risks to individuals and the measures that address them.",
                responsible="agent",
                accountable="DPO",
                inputs=("processing_description", "control_implementations"),
                outputs=("risk_assessment", "proposed_measures"),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role="Identify risks to individuals specifically, not risks to the organisation.",
                task_class="dpia_drafting",
                min_confidence=0.8,
                control_refs=("uk_gdpr:Art.35.7", "uk_gdpr:Art.25"),
            ),
            Activity(
                code="A3",
                what="Consult the data protection officer and, where appropriate, affected individuals.",
                responsible="DPO",
                accountable="DPO",
                inputs=("risk_assessment",),
                outputs=("dpo_opinion",),
                automation=Automation.MANUAL,
                control_refs=("uk_gdpr:Art.35.2",),
            ),
            Activity(
                code="A4",
                what="Decide whether residual high risk requires prior consultation with the regulator.",
                responsible="DPO",
                accountable="DPO",
                inputs=("risk_assessment", "dpo_opinion"),
                outputs=("consultation_decision",),
                automation=Automation.GATE,
                gate_type="privacy.dpia_decision",
                gate_reason="statutory",
                control_refs=("uk_gdpr:Art.36",),
                evidence=("dpia_report",),
            ),
        ),
    ),
    Process(
        code="PR-PRV-05",
        name="International transfers and retention",
        domain="PRV",
        purpose=(
            "Governs where personal data goes and how long it stays. Both are "
            "areas where the record and the reality drift apart quietly."
        ),
        owner_role="DPO",
        trigger="New transfer or recipient; retention schedule review",
        cadence=Cadence.ANNUAL,
        clauses={
            "uk_gdpr": ("Art.5.1.e", "Art.44", "Art.46", "Art.49"),
            "iso27001": ("A.5.14", "A.8.10"),
        },
        outputs=("transfer_register", "transfer_risk_assessment", "retention_schedule"),
        kpis=("Transfers with a valid mechanism", "Data held beyond its retention rule"),
        activities=(
            Activity(
                code="A1",
                what="Identify the transfer, the destination and the mechanism relied on.",
                responsible="agent",
                accountable="DPO",
                inputs=("processing_records", "supplier_register"),
                outputs=("transfer_register",),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role="Draft the entry and flag any transfer with no mechanism recorded.",
                task_class="classification",
                control_refs=("uk_gdpr:Art.44",),
            ),
            Activity(
                code="A2",
                what="Assess the destination's legal regime and any supplementary measures needed.",
                responsible="DPO",
                accountable="DPO",
                inputs=("transfer_register",),
                outputs=("transfer_risk_assessment",),
                automation=Automation.ASSIST,
                agent="privacy",
                ai_role=(
                    "Draft the assessment. Adequacy status and the sufficiency of "
                    "supplementary measures are legal judgements; present the "
                    "position, do not conclude it."
                ),
                task_class="dpia_drafting",
                min_confidence=0.85,
                control_refs=("uk_gdpr:Art.46",),
                evidence=("transfer_risk_assessment",),
            ),
            Activity(
                code="A3",
                what="Enforce retention: detect data held beyond its rule and raise disposal actions.",
                responsible="agent",
                accountable="DPO",
                trigger="Scheduled",
                inputs=("retention_schedule", "system_inventory"),
                outputs=("retention_exceptions",),
                automation=Automation.AUTO_NOTIFY,
                agent="privacy",
                ai_role=None,
                control_refs=("uk_gdpr:Art.5.1.e", "iso27001:A.8.10"),
                evidence=("retention_review_record",),
            ),
            Activity(
                code="A4",
                what="Authorise disposal.",
                responsible="DPO",
                accountable="DPO",
                inputs=("retention_exceptions",),
                outputs=("disposal_authorisation",),
                automation=Automation.GATE,
                gate_type="privacy.disposal_authorisation",
                gate_reason="irreversible",
                control_refs=("iso27001:A.8.10",),
            ),
        ),
    ),
)


# ==========================================================================
# SEC — Security operations
# ==========================================================================
SECURITY: tuple[Process, ...] = (
    Process(
        code="PR-SEC-01",
        name="Security event triage and incident response",
        domain="SEC",
        purpose="Takes a signal to a decision quickly, and routes anything touching personal data into the breach clock.",
        owner_role="CISO",
        trigger="Alert, report or detection",
        cadence=Cadence.EVENT,
        clauses={
            "iso27001": ("A.5.24", "A.5.25", "A.5.26", "A.5.27", "A.6.8"),
            "uk_gdpr": ("Art.32", "Art.33"),
            "iso22301": ("8.4",),
        },
        outputs=("incident_record", "triage_decision", "post_incident_review"),
        kpis=("Time to triage", "Incidents with lessons captured", "Repeat incidents by cause"),
        activities=(
            Activity(
                code="A1",
                what="Record the event and enrich it with asset, owner and data-classification context.",
                responsible="agent",
                accountable="CISO",
                trigger="Alert received",
                inputs=("alert", "asset_register", "processing_records"),
                outputs=("enriched_event",),
                automation=Automation.AUTO,
                agent="incident",
                control_refs=("iso27001:A.5.24",),
                sla_hours=1,
            ),
            Activity(
                code="A2",
                what="Triage: classify severity, type and whether personal data is involved.",
                responsible="agent",
                accountable="CISO",
                inputs=("enriched_event",),
                outputs=("triage_decision",),
                automation=Automation.ASSIST,
                agent="incident",
                ai_role=(
                    "Classify and give the reasoning. Where personal data "
                    "involvement is uncertain, say yes and let a person rule it "
                    "out: the cost of a false positive is a review, the cost of a "
                    "false negative is a missed statutory deadline."
                ),
                task_class="classification",
                min_confidence=0.8,
                control_refs=("iso27001:A.5.25",),
                sla_hours=2,
            ),
            Activity(
                code="A3",
                what="Contain and eradicate, recording each action as it is taken.",
                responsible="Operator",
                accountable="CISO",
                inputs=("triage_decision",),
                outputs=("response_actions",),
                automation=Automation.MANUAL,
                control_refs=("iso27001:A.5.26",),
            ),
            Activity(
                code="A4",
                what="Hand off to breach assessment where personal data is involved.",
                responsible="agent",
                accountable="DPO",
                inputs=("triage_decision",),
                outputs=("breach_referral",),
                automation=Automation.AUTO_NOTIFY,
                agent="orchestrator",
                control_refs=("uk_gdpr:Art.33",),
                sla_hours=2,
            ),
            Activity(
                code="A5",
                what="Conduct the post-incident review and feed the cause into improvement.",
                responsible="CISO",
                accountable="CISO",
                inputs=("response_actions",),
                outputs=("post_incident_review",),
                automation=Automation.ASSIST,
                agent="incident",
                ai_role="Draft the timeline and cause analysis from the recorded actions.",
                task_class="gap_analysis",
                control_refs=("iso27001:A.5.27",),
                evidence=("post_incident_review",),
            ),
        ),
    ),
    Process(
        code="PR-SEC-02",
        name="Vulnerability and patch management",
        domain="SEC",
        purpose="Finds technical weakness and closes it within the window its severity warrants.",
        owner_role="CISO",
        trigger="Scan results, advisory, or threat intelligence",
        cadence=Cadence.CONTINUOUS,
        clauses={
            "iso27001": ("A.8.8", "A.8.9", "A.8.19", "A.8.32"),
            "uk_gdpr": ("Art.32",),
        },
        outputs=("vulnerability_register", "remediation_actions", "exception_records"),
        kpis=("Vulnerabilities open beyond SLA by severity", "Patch coverage"),
        autonomy_tier="L3",
        activities=(
            Activity(
                code="A1",
                what="Ingest findings from scanners and advisories and deduplicate against the register.",
                responsible="agent",
                accountable="CISO",
                trigger="Continuous",
                inputs=("scanner_output", "advisories", "asset_register"),
                outputs=("vulnerability_register",),
                automation=Automation.AUTO,
                agent="evidence",
                control_refs=("iso27001:A.8.8",),
            ),
            Activity(
                code="A2",
                what="Prioritise by exploitability and by the business value of the affected asset.",
                responsible="agent",
                accountable="CISO",
                inputs=("vulnerability_register", "asset_register"),
                outputs=("prioritised_queue",),
                automation=Automation.AUTO,
                agent="risk_analyst",
                control_refs=("iso27001:A.8.8",),
            ),
            Activity(
                code="A3",
                what="Remediate within the window for the severity.",
                responsible="Operator",
                accountable="CISO",
                inputs=("prioritised_queue",),
                outputs=("remediation_actions",),
                automation=Automation.MANUAL,
                control_refs=("iso27001:A.8.8",),
            ),
            Activity(
                code="A4",
                what="Approve any exception where remediation is not possible within the window.",
                responsible="CISO",
                accountable="CISO",
                inputs=("prioritised_queue",),
                outputs=("exception_records",),
                automation=Automation.GATE,
                gate_type="security.vulnerability_exception",
                gate_reason="high_risk",
                control_refs=("iso27001:A.8.8",),
            ),
            Activity(
                code="A5",
                what="Verify closure by re-test rather than by assertion.",
                responsible="agent",
                accountable="CISO",
                inputs=("remediation_actions",),
                outputs=("verification_results",),
                automation=Automation.AUTO,
                agent="evidence",
                control_refs=("iso27001:A.8.8",),
                evidence=("vulnerability_closure_evidence",),
            ),
        ),
    ),
    Process(
        code="PR-SEC-03",
        name="Logging, monitoring and detection assurance",
        domain="SEC",
        purpose=(
            "Assures that the things meant to be watched are actually being "
            "watched. A detection control that stopped working is invisible "
            "until it is needed."
        ),
        owner_role="CISO",
        trigger="Continuous; monthly assurance review",
        cadence=Cadence.MONTHLY,
        clauses={
            "iso27001": ("A.8.15", "A.8.16", "A.8.17", "A.5.28"),
            "uk_gdpr": ("Art.32",),
        },
        outputs=("coverage_report", "detection_gaps"),
        kpis=("Log source coverage against the asset register", "Sources silent beyond threshold"),
        activities=(
            Activity(
                code="A1",
                what="Compare log sources actually reporting against the assets that should report.",
                responsible="agent",
                accountable="CISO",
                trigger="Daily",
                inputs=("log_sources", "asset_register"),
                outputs=("coverage_report", "silent_sources"),
                automation=Automation.AUTO,
                agent="evidence",
                control_refs=("iso27001:A.8.15", "iso27001:A.8.16"),
                evidence=("log_coverage_evidence",),
            ),
            Activity(
                code="A2",
                what="Raise a gap where a source has fallen silent or coverage has regressed.",
                responsible="agent",
                accountable="CISO",
                inputs=("silent_sources",),
                outputs=("detection_gaps",),
                automation=Automation.AUTO_NOTIFY,
                agent="control_assessor",
                control_refs=("iso27001:A.8.16",),
            ),
            Activity(
                code="A3",
                what="Confirm clock synchronisation and log protection remain in force.",
                responsible="agent",
                accountable="CISO",
                trigger="Weekly",
                inputs=("log_sources",),
                outputs=("integrity_check",),
                automation=Automation.AUTO,
                agent="evidence",
                control_refs=("iso27001:A.8.17",),
            ),
        ),
    ),
)


# ==========================================================================
# TPR — Third-party risk
# ==========================================================================
THIRD_PARTY: tuple[Process, ...] = (
    Process(
        code="PR-TPR-01",
        name="Supplier inherent risk and tiering",
        domain="TPR",
        purpose=(
            "Decides how much diligence an engagement actually warrants, before "
            "any is done. Tiering every supplier the same way is how diligence "
            "budgets are wasted on low-risk vendors and skipped on critical ones."
        ),
        owner_role="Control Owner",
        trigger="New engagement or material change of scope",
        cadence=Cadence.EVENT,
        clauses={
            "iso27001": ("A.5.19", "A.5.21"),
            "uk_gdpr": ("Art.28",),
            "iso22301": ("8.3",),
        },
        outputs=("inherent_risk_profile", "diligence_scope"),
        kpis=("Engagements tiered before contract", "Tier changes at reassessment"),
        activities=(
            Activity(
                code="A1",
                what="Capture the engagement: service, data accessed, criticality, jurisdictions, subcontracting.",
                responsible="Business Requestor",
                accountable="Control Owner",
                inputs=("engagement_request",),
                outputs=("engagement_profile",),
                automation=Automation.ASSIST,
                agent="third_party",
                ai_role="Draft the profile from the request and name every field left unanswered.",
                task_class="classification",
                control_refs=("iso27001:A.5.19",),
            ),
            Activity(
                code="A2",
                what="Score inherent risk and assign a tier that sets the diligence depth.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("engagement_profile",),
                outputs=("inherent_risk_profile", "diligence_scope"),
                automation=Automation.ASSIST,
                agent="third_party",
                ai_role=(
                    "Score exposure to the organisation — not the supplier's "
                    "controls, which are not yet known — and justify the tier."
                ),
                task_class="supplier_assessment",
                min_confidence=0.8,
                control_refs=("iso27001:A.5.19",),
            ),
        ),
    ),
    Process(
        code="PR-TPR-02",
        name="Supplier due diligence and approval",
        domain="TPR",
        purpose="Assesses the supplier's controls against the exposure, and approves or refuses the engagement.",
        owner_role="Control Owner",
        trigger="Completion of tiering",
        cadence=Cadence.EVENT,
        clauses={
            "iso27001": ("A.5.19", "A.5.20", "A.5.21", "A.5.22"),
            "uk_gdpr": ("Art.28", "Art.32", "Art.44"),
        },
        outputs=("assessment_report", "engagement_decision", "contract_requirements"),
        kpis=("Assessment turnaround", "Engagements approved with open conditions"),
        activities=(
            Activity(
                code="A1",
                what="Issue the questionnaire scoped to the tier and collect responses and certifications.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("diligence_scope",),
                outputs=("responses", "certifications"),
                automation=Automation.AUTO_NOTIFY,
                agent="third_party",
                control_refs=("iso27001:A.5.19",),
            ),
            Activity(
                code="A2",
                what="Assess responses domain by domain and reconcile them against evidence supplied.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("responses", "certifications"),
                outputs=("domain_scores", "concerns"),
                automation=Automation.ASSIST,
                agent="third_party",
                ai_role=(
                    "Score each domain and cite the response supporting it. Where "
                    "a certificate's scope does not cover the service being "
                    "bought, say so — that is the most common misread."
                ),
                task_class="supplier_assessment",
                min_confidence=0.8,
                control_refs=("iso27001:A.5.19", "uk_gdpr:Art.28"),
            ),
            Activity(
                code="A3",
                what="Determine residual risk and the conditions to attach to approval.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("domain_scores", "concerns", "inherent_risk_profile"),
                outputs=("residual_rating", "contract_requirements"),
                automation=Automation.ASSIST,
                agent="third_party",
                ai_role="Propose residual rating and the specific clauses the contract must carry.",
                task_class="supplier_assessment",
                control_refs=("iso27001:A.5.20", "uk_gdpr:Art.28.3"),
            ),
            Activity(
                code="A4",
                what="Approve or refuse the engagement.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("residual_rating",),
                outputs=("engagement_decision",),
                automation=Automation.GATE,
                gate_type="supplier.engagement",
                gate_reason="high_risk",
                control_refs=("iso27001:A.5.19",),
                evidence=("supplier_approval_record",),
            ),
            Activity(
                code="A5",
                what="Confirm the executed contract carries the required clauses before service begins.",
                responsible="DPO",
                accountable="DPO",
                inputs=("contract_requirements", "executed_contract"),
                outputs=("contract_confirmation",),
                automation=Automation.GATE,
                gate_type="supplier.contract",
                gate_reason="statutory",
                control_refs=("iso27001:A.5.20", "uk_gdpr:Art.28.3"),
            ),
        ),
    ),
    Process(
        code="PR-TPR-03",
        name="Ongoing supplier monitoring and exit",
        domain="TPR",
        purpose=(
            "Watches the supplier between assessments and governs exit. Most "
            "third-party incidents happen to suppliers that passed diligence "
            "some time ago."
        ),
        owner_role="Control Owner",
        trigger="Continuous monitoring; contract renewal; termination",
        cadence=Cadence.CONTINUOUS,
        clauses={
            "iso27001": ("A.5.22", "A.5.23"),
            "iso22301": ("8.3",),
            "uk_gdpr": ("Art.28",),
        },
        outputs=("monitoring_signals", "reassessment_trigger", "exit_record"),
        kpis=("Critical suppliers reassessed within cycle", "Exits with data return or destruction evidenced"),
        activities=(
            Activity(
                code="A1",
                what="Monitor for supplier events: breaches, certificate expiry, adverse media, financial distress.",
                responsible="agent",
                accountable="Control Owner",
                trigger="Continuous",
                inputs=("supplier_register", "external_feeds"),
                outputs=("monitoring_signals",),
                automation=Automation.AUTO,
                agent="third_party",
                control_refs=("iso27001:A.5.22",),
            ),
            Activity(
                code="A2",
                what="Decide whether a signal warrants reassessment ahead of cycle.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("monitoring_signals",),
                outputs=("reassessment_trigger",),
                automation=Automation.ASSIST,
                agent="third_party",
                ai_role="Recommend reassess or note, with the reasoning.",
                task_class="classification",
                min_confidence=0.8,
                control_refs=("iso27001:A.5.22",),
            ),
            Activity(
                code="A3",
                what="On exit, confirm data return or destruction and access revocation.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("termination_notice",),
                outputs=("exit_record",),
                automation=Automation.ASSIST,
                agent="third_party",
                ai_role="Assemble the exit checklist and identify what remains outstanding.",
                task_class="evidence_summary",
                control_refs=("iso27001:A.5.22", "uk_gdpr:Art.28.3.g"),
                evidence=("supplier_exit_record",),
            ),
        ),
    ),
)


# ==========================================================================
# RES — Operational resilience
# ==========================================================================
RESILIENCE: tuple[Process, ...] = (
    Process(
        code="PR-RES-01",
        name="Business impact analysis",
        domain="RES",
        purpose="Establishes what must keep running, how quickly it must recover, and how much data loss is tolerable.",
        owner_role="Control Owner",
        trigger="Annual review, new activity, or material change",
        cadence=Cadence.ANNUAL,
        clauses={"iso22301": ("8.2", "8.2.2", "8.2.3"), "iso27001": ("A.5.29", "A.5.30")},
        outputs=("bia_record", "recovery_objectives", "dependency_map"),
        kpis=("Prioritised activities with current BIA", "RTOs shorter than MTPD"),
        activities=(
            Activity(
                code="A1",
                what="Identify the prioritised activity and map its dependencies: people, systems, suppliers, sites.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("activity_register", "asset_register", "supplier_register"),
                outputs=("dependency_map",),
                automation=Automation.ASSIST,
                agent="resilience",
                ai_role="Draft the dependency map from the registers and flag single points of failure.",
                task_class="bia_drafting",
                control_refs=("iso22301:8.2.2",),
            ),
            Activity(
                code="A2",
                what="Analyse impact over time and derive MTPD, RTO, RPO and the minimum objective.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("dependency_map",),
                outputs=("recovery_objectives",),
                automation=Automation.ASSIST,
                agent="resilience",
                ai_role="Draft the impact profile and derive objectives; the RTO must be shorter than the MTPD.",
                task_class="bia_drafting",
                min_confidence=0.75,
                control_refs=("iso22301:8.2.2",),
            ),
            Activity(
                code="A3",
                what="Approve the analysis and its recovery objectives.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("recovery_objectives",),
                outputs=("bia_record",),
                automation=Automation.GATE,
                gate_type="resilience.bia_signoff",
                gate_reason="high_risk",
                control_refs=("iso22301:8.2.3",),
                evidence=("approved_bia",),
            ),
        ),
    ),
    Process(
        code="PR-RES-02",
        name="Continuity strategy and plan development",
        domain="RES",
        purpose="Turns approved recovery objectives into arrangements that can actually meet them.",
        owner_role="Control Owner",
        trigger="Approved BIA, or change to the estate",
        cadence=Cadence.ANNUAL,
        clauses={"iso22301": ("8.3", "8.3.1", "8.3.2", "8.3.3", "8.4", "8.4.1", "8.4.2")},
        outputs=("continuity_strategy", "continuity_plan", "resource_requirements"),
        kpis=("Plans approved and current", "Plans meeting their stated RTO at exercise"),
        activities=(
            Activity(
                code="A1",
                what="Identify strategy options that meet the RTO within available resources.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("bia_record",),
                outputs=("strategy_options",),
                automation=Automation.ASSIST,
                agent="resilience",
                ai_role="Draft options with cost, achievable recovery time and the gap to the objective.",
                task_class="policy_drafting",
                control_refs=("iso22301:8.3.2",),
            ),
            Activity(
                code="A2",
                what="Select the strategy and specify the resources it requires.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("strategy_options",),
                outputs=("continuity_strategy", "resource_requirements"),
                automation=Automation.MANUAL,
                control_refs=("iso22301:8.3.3",),
            ),
            Activity(
                code="A3",
                what="Write the plan: invocation criteria, roles, procedures, communications.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("continuity_strategy",),
                outputs=("draft_plan",),
                automation=Automation.ASSIST,
                agent="resilience",
                ai_role="Draft the plan in the house structure and flag anything the strategy leaves unresolved.",
                task_class="policy_drafting",
                control_refs=("iso22301:8.4.2",),
            ),
            Activity(
                code="A4",
                what="Approve the plan.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("draft_plan",),
                outputs=("continuity_plan",),
                automation=Automation.GATE,
                gate_type="resilience.plan_approval",
                gate_reason="high_risk",
                control_refs=("iso22301:8.4.1",),
                evidence=("approved_continuity_plan",),
            ),
        ),
    ),
    Process(
        code="PR-RES-03",
        name="Exercising and testing",
        domain="RES",
        purpose=(
            "Proves the plan works. An unexercised plan is a document, and "
            "clause 8.5 exists because organisations discover this during the "
            "incident rather than before it."
        ),
        owner_role="Control Owner",
        trigger="Exercise schedule; significant change to the plan or estate",
        cadence=Cadence.ANNUAL,
        clauses={"iso22301": ("8.5", "9.1"), "iso27001": ("A.5.29", "A.5.30")},
        outputs=("exercise_report", "achieved_objectives", "improvement_actions"),
        kpis=("Plans exercised within 12 months", "Exercises meeting stated RTO", "Findings closed"),
        activities=(
            Activity(
                code="A1",
                what="Design a scenario that genuinely tests the plan's assumptions.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("continuity_plan", "risk_register", "incident_history"),
                outputs=("exercise_scenario",),
                automation=Automation.ASSIST,
                agent="resilience",
                ai_role=(
                    "Propose a scenario that stresses the plan's weakest "
                    "assumption, drawn from the risk register and real incidents."
                ),
                task_class="bia_drafting",
                control_refs=("iso22301:8.5",),
            ),
            Activity(
                code="A2",
                what="Run the exercise and record what actually happened against the clock.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("exercise_scenario",),
                outputs=("exercise_log", "achieved_objectives"),
                automation=Automation.MANUAL,
                control_refs=("iso22301:8.5",),
                evidence=("exercise_record",),
            ),
            Activity(
                code="A3",
                what="Compare achieved recovery against the objective and raise a gap where it was missed.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("exercise_log", "recovery_objectives"),
                outputs=("exercise_report", "improvement_actions"),
                automation=Automation.AUTO_NOTIFY,
                agent="resilience",
                ai_role="Report the shortfall plainly; an exercise that missed its RTO is a finding, not a pass.",
                task_class="gap_analysis",
                control_refs=("iso22301:8.5", "iso22301:10.1"),
                evidence=("exercise_report",),
            ),
        ),
    ),
    Process(
        code="PR-RES-04",
        name="Crisis invocation and recovery",
        domain="RES",
        purpose="Governs live invocation, where speed matters and the decision is irreversible.",
        owner_role="CISO",
        trigger="Disruption meeting invocation criteria",
        cadence=Cadence.EVENT,
        clauses={"iso22301": ("8.4", "8.4.3", "8.4.4", "8.4.5")},
        outputs=("invocation_record", "recovery_log", "stand_down_record"),
        kpis=("Time from disruption to invocation decision", "Recovery within RTO"),
        autonomy_tier="L1",
        notes=(
            "Autonomy is deliberately lowest here. During a live incident the "
            "platform informs and records; it does not act. An agent invoking "
            "failover on a false positive would cause the outage it was meant to "
            "contain."
        ),
        activities=(
            Activity(
                code="A1",
                what="Assess the disruption against invocation criteria and brief the response team.",
                responsible="agent",
                accountable="CISO",
                inputs=("disruption_report", "continuity_plan"),
                outputs=("invocation_assessment",),
                automation=Automation.ASSIST,
                agent="resilience",
                ai_role="Compare the situation against the criteria and present the position. Do not conclude.",
                task_class="classification",
                min_confidence=0.9,
                control_refs=("iso22301:8.4.3",),
                sla_hours=1,
            ),
            Activity(
                code="A2",
                what="Decide to invoke.",
                responsible="CISO",
                accountable="CISO",
                inputs=("invocation_assessment",),
                outputs=("invocation_record",),
                automation=Automation.GATE,
                gate_type="resilience.live_failover",
                gate_reason="irreversible",
                control_refs=("iso22301:8.4.3",),
                evidence=("invocation_decision",),
            ),
            Activity(
                code="A3",
                what="Record actions, decisions and communications throughout recovery.",
                responsible="agent",
                accountable="CISO",
                trigger="Continuous during invocation",
                inputs=("invocation_record",),
                outputs=("recovery_log",),
                automation=Automation.AUTO,
                agent="evidence",
                control_refs=("iso22301:8.4.4",),
                evidence=("crisis_log",),
            ),
            Activity(
                code="A4",
                what="Stand down and begin the post-incident review.",
                responsible="CISO",
                accountable="CISO",
                inputs=("recovery_log",),
                outputs=("stand_down_record",),
                automation=Automation.GATE,
                gate_type="resilience.stand_down",
                gate_reason="high_risk",
                control_refs=("iso22301:8.4.5",),
            ),
        ),
    ),
)


# ==========================================================================
# PPL — People and access
# ==========================================================================
PEOPLE: tuple[Process, ...] = (
    Process(
        code="PR-PPL-01",
        name="Joiner, mover, leaver",
        domain="PPL",
        purpose="Ensures access matches role at all times, and ends promptly when it should.",
        owner_role="Security Admin",
        trigger="HR event",
        cadence=Cadence.EVENT,
        clauses={
            "iso27001": ("A.5.16", "A.5.17", "A.5.18", "A.6.1", "A.6.2", "A.6.5"),
            "uk_gdpr": ("Art.32",),
        },
        outputs=("provisioning_record", "revocation_record"),
        kpis=("Leaver access revoked within SLA", "Orphaned accounts detected"),
        activities=(
            Activity(
                code="A1",
                what="Derive the entitlement set from the role and provision it.",
                responsible="agent",
                accountable="Security Admin",
                trigger="HR joiner or mover event",
                inputs=("hr_event", "role_entitlement_map"),
                outputs=("provisioning_plan",),
                automation=Automation.AUTO,
                agent="orchestrator",
                control_refs=("iso27001:A.5.16", "iso27001:A.5.18"),
            ),
            Activity(
                code="A2",
                what="Approve any entitlement beyond the role's standard set.",
                responsible="Security Admin",
                accountable="Security Admin",
                inputs=("provisioning_plan",),
                outputs=("approved_exception",),
                automation=Automation.GATE,
                gate_type="access.privileged_grant",
                gate_reason="high_risk",
                control_refs=("iso27001:A.5.18",),
            ),
            Activity(
                code="A3",
                what="Revoke access on the leaver date and confirm it took effect.",
                responsible="agent",
                accountable="Security Admin",
                trigger="HR leaver event",
                inputs=("hr_event",),
                outputs=("revocation_record",),
                automation=Automation.AUTO,
                agent="orchestrator",
                control_refs=("iso27001:A.5.18", "iso27001:A.6.5"),
                evidence=("access_revocation_evidence",),
                sla_hours=24,
            ),
            Activity(
                code="A4",
                what="Reconcile accounts against the HR record and raise any that do not match.",
                responsible="agent",
                accountable="Security Admin",
                trigger="Daily",
                inputs=("account_inventory", "hr_record"),
                outputs=("orphan_findings",),
                automation=Automation.AUTO_NOTIFY,
                agent="evidence",
                control_refs=("iso27001:A.5.16",),
            ),
        ),
    ),
    Process(
        code="PR-PPL-02",
        name="Access recertification",
        domain="PPL",
        purpose="Periodically re-justifies who has what, and removes what cannot be justified.",
        owner_role="Security Admin",
        trigger="Recertification cycle by system criticality",
        cadence=Cadence.QUARTERLY,
        clauses={"iso27001": ("A.5.16", "A.5.18", "A.8.2")},
        outputs=("recertification_campaign", "revocations"),
        kpis=("Campaign completion rate", "Entitlements revoked at review"),
        activities=(
            Activity(
                code="A1",
                what="Assemble the review pack per reviewer, with last-used data to make the decision informed.",
                responsible="agent",
                accountable="Security Admin",
                inputs=("entitlement_inventory", "usage_telemetry"),
                outputs=("review_packs",),
                automation=Automation.AUTO,
                agent="evidence",
                control_refs=("iso27001:A.5.18",),
            ),
            Activity(
                code="A2",
                what="Highlight entitlements that look anomalous or unused.",
                responsible="agent",
                accountable="Security Admin",
                inputs=("review_packs",),
                outputs=("flagged_entitlements",),
                automation=Automation.ASSIST,
                agent="control_assessor",
                ai_role="Flag outliers against role peers and long-unused access, with the reasoning.",
                task_class="classification",
                control_refs=("iso27001:A.5.18",),
            ),
            Activity(
                code="A3",
                what="Review and decide on each entitlement.",
                responsible="Control Owner",
                accountable="Security Admin",
                inputs=("review_packs", "flagged_entitlements"),
                outputs=("recertification_decisions",),
                automation=Automation.GATE,
                gate_type="access.recertification",
                gate_reason="high_risk",
                control_refs=("iso27001:A.5.18",),
                evidence=("recertification_record",),
            ),
            Activity(
                code="A4",
                what="Execute revocations and confirm they took effect.",
                responsible="agent",
                accountable="Security Admin",
                inputs=("recertification_decisions",),
                outputs=("revocations",),
                automation=Automation.AUTO,
                agent="orchestrator",
                control_refs=("iso27001:A.5.18",),
            ),
        ),
    ),
    Process(
        code="PR-PPL-03",
        name="Awareness and competence",
        domain="PPL",
        purpose="Maintains and evidences the competence the standards require of the people operating controls.",
        owner_role="Security Admin",
        trigger="Onboarding; annual cycle; role change",
        cadence=Cadence.ANNUAL,
        clauses={"iso27001": ("7.2", "7.3", "A.6.3"), "iso22301": ("7.2", "7.3"), "uk_gdpr": ("Art.39",)},
        outputs=("competence_record", "training_completion"),
        kpis=("Training completion by due date", "Roles with a defined competence profile"),
        activities=(
            Activity(
                code="A1",
                what="Determine the competence each role requires and identify the shortfall.",
                responsible="agent",
                accountable="Security Admin",
                inputs=("role_definitions", "competence_records"),
                outputs=("competence_gaps",),
                automation=Automation.ASSIST,
                agent="control_assessor",
                ai_role="Map role to required competence and name the gap for each person.",
                task_class="gap_analysis",
                control_refs=("iso27001:7.2",),
            ),
            Activity(
                code="A2",
                what="Assign and track training to close the shortfall.",
                responsible="agent",
                accountable="Security Admin",
                inputs=("competence_gaps",),
                outputs=("training_completion",),
                automation=Automation.AUTO_NOTIFY,
                agent="orchestrator",
                control_refs=("iso27001:7.2", "iso27001:A.6.3"),
                evidence=("training_evidence",),
            ),
        ),
    ),
)


# ==========================================================================
# CHG — Change and secure development
# ==========================================================================
CHANGE: tuple[Process, ...] = (
    Process(
        code="PR-CHG-01",
        name="Change management",
        domain="CHG",
        purpose="Ensures change is assessed for security, privacy and continuity impact before it reaches production.",
        owner_role="Control Owner",
        trigger="Change request raised",
        cadence=Cadence.EVENT,
        clauses={
            "iso27001": ("8.1", "A.8.32", "A.8.9"),
            "iso22301": ("8.1",),
            "uk_gdpr": ("Art.25", "Art.35"),
        },
        outputs=("change_record", "impact_assessment", "approval_decision"),
        kpis=("Emergency changes as a share of total", "Changes reversed after release"),
        activities=(
            Activity(
                code="A1",
                what="Assess the change for security, privacy and continuity impact.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("change_request", "asset_register", "processing_records"),
                outputs=("impact_assessment",),
                automation=Automation.ASSIST,
                agent="control_assessor",
                ai_role=(
                    "Identify affected controls, processing activities and "
                    "recovery objectives, and say whether a DPIA is triggered."
                ),
                task_class="control_assessment",
                min_confidence=0.8,
                control_refs=("iso27001:8.1", "uk_gdpr:Art.25"),
            ),
            Activity(
                code="A2",
                what="Decide go or no-go.",
                responsible="Control Owner",
                accountable="Control Owner",
                inputs=("impact_assessment",),
                outputs=("approval_decision",),
                automation=Automation.GATE,
                gate_type="change.go_no_go",
                gate_reason="high_risk",
                control_refs=("iso27001:A.8.32",),
                evidence=("change_approval_record",),
            ),
            Activity(
                code="A3",
                what="Update affected records after release: controls, processing records, recovery objectives.",
                responsible="agent",
                accountable="Control Owner",
                inputs=("approval_decision", "release_record"),
                outputs=("record_updates",),
                automation=Automation.AUTO_NOTIFY,
                agent="orchestrator",
                control_refs=("iso27001:8.1",),
            ),
        ),
    ),
    Process(
        code="PR-CHG-02",
        name="Secure development and go-live assurance",
        domain="CHG",
        purpose="Builds requirements in at design time and confirms them before release rather than after.",
        owner_role="CISO",
        trigger="New system or significant feature entering design",
        cadence=Cadence.EVENT,
        clauses={
            "iso27001": ("A.8.25", "A.8.26", "A.8.27", "A.8.28", "A.8.29", "A.8.31"),
            "uk_gdpr": ("Art.25",),
        },
        outputs=("security_requirements", "test_results", "golive_decision"),
        kpis=("Findings raised at design versus at release", "Go-lives with open high findings"),
        activities=(
            Activity(
                code="A1",
                what="Derive security and privacy requirements for the design.",
                responsible="agent",
                accountable="CISO",
                inputs=("design_document", "processing_records", "control_library"),
                outputs=("security_requirements",),
                automation=Automation.ASSIST,
                agent="control_assessor",
                ai_role="Derive requirements from the control library and data protection by design obligations.",
                task_class="control_assessment",
                control_refs=("iso27001:A.8.25", "uk_gdpr:Art.25"),
            ),
            Activity(
                code="A2",
                what="Verify requirements are met by test evidence before release.",
                responsible="agent",
                accountable="CISO",
                inputs=("security_requirements", "test_evidence"),
                outputs=("test_results",),
                automation=Automation.ASSIST,
                agent="evidence",
                ai_role="State which requirements are evidenced and which are asserted but not demonstrated.",
                task_class="evidence_summary",
                min_confidence=0.8,
                control_refs=("iso27001:A.8.29",),
            ),
            Activity(
                code="A3",
                what="Approve go-live.",
                responsible="CISO",
                accountable="CISO",
                inputs=("test_results",),
                outputs=("golive_decision",),
                automation=Automation.GATE,
                gate_type="golive.security_by_design",
                gate_reason="irreversible",
                control_refs=("iso27001:A.8.31",),
                evidence=("golive_approval",),
            ),
        ),
    ),
)


# ==========================================================================
# AIG — AI governance
# ==========================================================================
AI_GOVERNANCE: tuple[Process, ...] = (
    Process(
        code="PR-AIG-01",
        name="AI system inventory and risk classification",
        domain="AIG",
        purpose=(
            "Maintains the inventory of AI systems the organisation builds or "
            "deploys, with a risk classification for each. This is the "
            "foundational record for AI governance and the first thing any AI "
            "regulator or customer assurance questionnaire asks for."
        ),
        owner_role="CISO",
        trigger="New AI system or model; change of purpose; annual review",
        cadence=Cadence.QUARTERLY,
        clauses={
            "iso27001": ("A.5.9", "A.8.25"),
            "uk_gdpr": ("Art.22", "Art.35"),
        },
        outputs=("ai_inventory", "risk_classification", "transparency_obligations"),
        kpis=("AI systems inventoried", "Systems with a current classification"),
        notes=(
            "Scope deliberately includes this platform's own agents. A GRC "
            "system that automates compliance with AI and cannot evidence the "
            "governance of that AI is arguing against itself."
        ),
        activities=(
            Activity(
                code="A1",
                what="Discover and record AI systems in use, including embedded and third-party models.",
                responsible="agent",
                accountable="CISO",
                inputs=("system_inventory", "supplier_register", "model_gateway_config"),
                outputs=("ai_inventory",),
                automation=Automation.ASSIST,
                agent="regulatory_watch",
                ai_role="Draft the inventory entry, including provider, model, purpose and data used.",
                task_class="classification",
                control_refs=("iso27001:A.5.9",),
            ),
            Activity(
                code="A2",
                what="Classify each system's risk and determine which obligations attach.",
                responsible="DPO",
                accountable="CISO",
                inputs=("ai_inventory", "obligation_register"),
                outputs=("risk_classification", "transparency_obligations"),
                automation=Automation.ASSIST,
                agent="regulatory_watch",
                ai_role=(
                    "Present the classification the criteria point to and the "
                    "obligations that would follow. Classification is a legal "
                    "determination; present it, do not decide it."
                ),
                task_class="classification",
                min_confidence=0.9,
                control_refs=("uk_gdpr:Art.35",),
            ),
            Activity(
                code="A3",
                what="Approve the classification and the obligations accepted for each system.",
                responsible="CISO",
                accountable="CISO",
                inputs=("risk_classification",),
                outputs=("approved_classification",),
                automation=Automation.GATE,
                gate_type="ai.risk_classification",
                gate_reason="statutory",
                control_refs=("iso27001:A.5.9",),
                evidence=("ai_classification_record",),
            ),
        ),
    ),
    Process(
        code="PR-AIG-02",
        name="AI human oversight and decision accountability",
        domain="AIG",
        purpose=(
            "Assures that every AI-influenced decision has a human accountable "
            "for it, that the person can understand and override the output, and "
            "that the record shows which is which."
        ),
        owner_role="CISO",
        trigger="Continuous; on any new agent or autonomy change",
        cadence=Cadence.CONTINUOUS,
        clauses={
            "iso27001": ("A.5.2", "A.5.3", "A.8.16"),
            "uk_gdpr": ("Art.22",),
        },
        outputs=("oversight_register", "override_log", "autonomy_decisions"),
        kpis=("AI outputs accepted without review", "Override rate by agent", "Low-confidence escalations honoured"),
        autonomy_tier="L2",
        activities=(
            Activity(
                code="A1",
                what="Record, for each agent, its scope, its autonomy tier and the person accountable.",
                responsible="CISO",
                accountable="CISO",
                inputs=("agent_registry",),
                outputs=("oversight_register",),
                automation=Automation.MANUAL,
                control_refs=("iso27001:A.5.2",),
                evidence=("ai_oversight_register",),
            ),
            Activity(
                code="A2",
                what="Monitor acceptance and override rates per agent and per task class.",
                responsible="agent",
                accountable="CISO",
                trigger="Continuous",
                inputs=("model_invocations", "gate_decisions", "audit_log"),
                outputs=("oversight_metrics",),
                automation=Automation.AUTO,
                agent="reporting",
                control_refs=("iso27001:A.8.16",),
            ),
            Activity(
                code="A3",
                what=(
                    "Detect rubber-stamping: an agent whose output is approved "
                    "essentially always, or reviewed faster than it could be read."
                ),
                responsible="agent",
                accountable="CISO",
                inputs=("oversight_metrics",),
                outputs=("oversight_findings",),
                automation=Automation.AUTO_NOTIFY,
                agent="control_assessor",
                ai_role=(
                    "Flag where human review appears nominal. Oversight that is "
                    "recorded but not exercised is the failure mode this control "
                    "exists to catch."
                ),
                task_class="control_assessment",
                min_confidence=0.75,
                control_refs=("iso27001:A.5.3", "uk_gdpr:Art.22"),
            ),
            Activity(
                code="A4",
                what="Approve any change to an agent's autonomy tier or scope.",
                responsible="CISO",
                accountable="CISO",
                inputs=("oversight_findings", "proposed_change"),
                outputs=("autonomy_decisions",),
                automation=Automation.GATE,
                gate_type="ai.autonomy_change",
                gate_reason="high_risk",
                control_refs=("iso27001:A.5.2",),
                evidence=("autonomy_change_record",),
            ),
        ),
    ),
    Process(
        code="PR-AIG-03",
        name="AI performance monitoring and drift",
        domain="AIG",
        purpose=(
            "Watches whether the AI is still doing what it was assessed as "
            "doing. Model versions change under the platform's feet, and a "
            "provider upgrade is a change to a control."
        ),
        owner_role="CISO",
        trigger="Continuous; on model or prompt version change",
        cadence=Cadence.CONTINUOUS,
        clauses={"iso27001": ("9.1", "A.8.16", "A.8.32")},
        outputs=("performance_baseline", "drift_findings", "revalidation_record"),
        kpis=("Confidence trend by task class", "Time from model change to revalidation"),
        activities=(
            Activity(
                code="A1",
                what="Baseline output quality per agent and task class: confidence, override rate, correction rate.",
                responsible="agent",
                accountable="CISO",
                inputs=("model_invocations", "gate_decisions"),
                outputs=("performance_baseline",),
                automation=Automation.AUTO,
                agent="reporting",
                control_refs=("iso27001:9.1",),
            ),
            Activity(
                code="A2",
                what="Detect drift against the baseline, and detect provider model or prompt version change.",
                responsible="agent",
                accountable="CISO",
                trigger="Continuous",
                inputs=("performance_baseline", "model_invocations", "config_versions"),
                outputs=("drift_findings",),
                automation=Automation.AUTO_NOTIFY,
                agent="reporting",
                control_refs=("iso27001:A.8.16", "iso27001:A.8.32"),
            ),
            Activity(
                code="A3",
                what="Revalidate the affected task classes against a held-out set before relying on them again.",
                responsible="agent",
                accountable="CISO",
                inputs=("drift_findings", "validation_set"),
                outputs=("revalidation_record",),
                automation=Automation.ASSIST,
                agent="control_assessor",
                ai_role="Compare current output against the reference set and report the delta.",
                task_class="control_assessment",
                min_confidence=0.8,
                control_refs=("iso27001:A.8.32",),
                evidence=("ai_revalidation_record",),
            ),
            Activity(
                code="A4",
                what="Approve continued reliance, or reduce autonomy until the shortfall is resolved.",
                responsible="CISO",
                accountable="CISO",
                inputs=("revalidation_record",),
                outputs=("reliance_decision",),
                automation=Automation.GATE,
                gate_type="ai.model_revalidation",
                gate_reason="high_risk",
                control_refs=("iso27001:A.8.32",),
            ),
        ),
    ),
)
