"""Starter workflow definitions.

Each activity is the five-part contract from the SOP manual — What, Who, When,
Input, Output — plus the AI's role and the control binding. ``automation``
decides whether the engine runs the step or stops for a person:

    auto         the engine completes it
    auto_notify  the engine completes it and tells the owner
    gate         the engine raises an approval gate and waits
    assist       a person performs it; the AI drafts

Gates appear where an action is irreversible, statutory, high-risk or where the
model's confidence is low. Everything else runs straight through.
"""

from __future__ import annotations

WORKFLOWS: list[dict] = [
    {
        "wf_code": "WF-22",
        "name": "Risk assessment and treatment",
        "family": "RSK",
        "pillars": ["security", "gdpr", "bcp"],
        "tier": "L3",
        "owner_role": "Risk Officer",
        "activities": [
            {
                "code": "A1",
                "what": "Capture the risk: asset, threat, vulnerability and business context.",
                "responsible": "agent",
                "accountable_role": "Risk Officer",
                "ai_role": "Draft the risk statement from the trigger and cite its sources.",
                "task_class": "risk_drafting",
                "automation": "auto",
                "inputs": ["trigger_event", "asset_register"],
                "outputs": ["risk_statement"],
                "control": {"iso27001": "6.1.2"},
            },
            {
                "code": "A2",
                "what": "Score inherent likelihood and impact on the 5×5 matrix.",
                "responsible": "agent",
                "accountable_role": "Risk Officer",
                "ai_role": "Propose scores with the reasoning that supports each.",
                "task_class": "risk_drafting",
                "automation": "auto",
                "inputs": ["risk_statement"],
                "outputs": ["inherent_score"],
                "control": {"iso27001": "6.1.2", "min_confidence": 0.7},
            },
            {
                "code": "A3",
                "what": "Identify the controls already in place and score residual risk.",
                "responsible": "agent",
                "accountable_role": "Risk Officer",
                "ai_role": "Map existing control implementations to the risk and re-score.",
                "task_class": "control_assessment",
                "automation": "auto",
                "inputs": ["inherent_score", "control_implementations"],
                "outputs": ["residual_score", "linked_controls"],
                "control": {"iso27001": "6.1.3"},
            },
            {
                "code": "A4",
                "what": "Agree the treatment strategy and plan.",
                "responsible": "human",
                "accountable_role": "Risk Officer",
                "ai_role": "Draft treatment options with cost and effect on the residual score.",
                "task_class": "risk_drafting",
                "automation": "assist",
                "inputs": ["residual_score"],
                "outputs": ["treatment_plan"],
                "control": {"iso27001": "6.1.3"},
            },
            {
                "code": "A5",
                "what": "Accept the residual risk where it exceeds appetite.",
                "responsible": "human",
                "accountable_role": "Risk Officer",
                "automation": "gate",
                "gate_type": "risk.residual_acceptance",
                "gate_reason": "high_risk",
                "inputs": ["residual_score", "treatment_plan"],
                "outputs": ["acceptance_record"],
                "control": {"iso27001": "6.1.3", "high_risk": True},
            },
        ],
    },
    {
        "wf_code": "WF-26",
        "name": "Control assessment and gap remediation",
        "family": "MON",
        "pillars": ["security", "bcp", "gdpr"],
        "tier": "L3",
        "owner_role": "Control Owner",
        "activities": [
            {
                "code": "A1",
                "what": "Collect the current evidence for the control under assessment.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Gather linked evidence records and flag anything expired.",
                "task_class": "evidence_summary",
                "automation": "auto",
                "inputs": ["control_implementation"],
                "outputs": ["evidence_bundle"],
            },
            {
                "code": "A2",
                "what": "Assess the implementation against the requirement and rate its maturity.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Assess and cite the evidence supporting each conclusion.",
                "task_class": "control_assessment",
                "automation": "auto",
                "inputs": ["evidence_bundle", "framework_control"],
                "outputs": ["assessment", "maturity"],
                "control": {"min_confidence": 0.75},
            },
            {
                "code": "A3",
                "what": "Raise gaps for every shortfall, with severity and a remediation plan.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Draft the gap and a proportionate remediation plan.",
                "task_class": "gap_analysis",
                "automation": "auto_notify",
                "inputs": ["assessment"],
                "outputs": ["gaps"],
            },
            {
                "code": "A4",
                "what": "Attest the control status for the compliance record.",
                "responsible": "human",
                "accountable_role": "Control Owner",
                "automation": "gate",
                "gate_type": "change.implementation",
                "gate_reason": "statutory",
                "inputs": ["assessment", "gaps"],
                "outputs": ["attestation"],
                "control": {"statutory": True},
            },
        ],
    },
    {
        "wf_code": "WF-08",
        "name": "Data subject request",
        "family": "APD",
        "pillars": ["gdpr"],
        "tier": "L3",
        "owner_role": "DPO",
        "activities": [
            {
                "code": "A1",
                "what": "Log the request, classify its type and start the statutory clock.",
                "responsible": "agent",
                "accountable_role": "DPO",
                "ai_role": "Classify the request type and compute the statutory deadline.",
                "task_class": "classification",
                "automation": "auto",
                "inputs": ["request"],
                "outputs": ["dsar_record"],
                "control": {"gdpr": "Art.12"},
            },
            {
                "code": "A2",
                "what": "Verify the identity of the requester.",
                "responsible": "human",
                "accountable_role": "DPO",
                "ai_role": "Check the evidence supplied against the verification standard.",
                "automation": "assist",
                "inputs": ["dsar_record"],
                "outputs": ["identity_verified"],
                "control": {"gdpr": "Art.12"},
            },
            {
                "code": "A3",
                "what": "Search the estate and assemble the response pack.",
                "responsible": "agent",
                "accountable_role": "DPO",
                "ai_role": "Assemble the pack and flag third-party data for redaction.",
                "task_class": "evidence_summary",
                "automation": "auto",
                "inputs": ["identity_verified", "processing_records"],
                "outputs": ["response_pack"],
                "control": {"gdpr": "Art.15"},
            },
            {
                "code": "A4",
                "what": "Release the response to the data subject.",
                "responsible": "human",
                "accountable_role": "DPO",
                "automation": "gate",
                "gate_type": "privacy.dsar_release",
                "gate_reason": "statutory",
                "inputs": ["response_pack"],
                "outputs": ["release_record"],
                "control": {"gdpr": "Art.15", "statutory": True, "irreversible": True},
            },
        ],
    },
    {
        "wf_code": "WF-17",
        "name": "Personal data breach assessment and notification",
        "family": "OPS",
        "pillars": ["gdpr", "security"],
        "tier": "L3",
        "owner_role": "DPO",
        "activities": [
            {
                "code": "A1",
                "what": "Confirm whether the incident is a personal data breach and start the 72-hour clock.",
                "responsible": "agent",
                "accountable_role": "DPO",
                "ai_role": "Assess the incident against the breach definition and cite the basis.",
                "task_class": "classification",
                "automation": "auto",
                "inputs": ["incident"],
                "outputs": ["breach_record", "clock_started_at"],
                "control": {"gdpr": "Art.33", "statutory": True},
            },
            {
                "code": "A2",
                "what": "Assess the risk to the rights and freedoms of the individuals affected.",
                "responsible": "agent",
                "accountable_role": "DPO",
                "ai_role": "Draft the risk assessment with the factors that drive it.",
                "task_class": "dpia_drafting",
                "automation": "auto",
                "inputs": ["breach_record"],
                "outputs": ["risk_to_individuals"],
                "control": {"gdpr": "Art.33", "min_confidence": 0.8},
            },
            {
                "code": "A3",
                "what": "Decide whether to notify the supervisory authority.",
                "responsible": "human",
                "accountable_role": "DPO",
                "automation": "gate",
                "gate_type": "privacy.breach_notify",
                "gate_reason": "statutory",
                "inputs": ["risk_to_individuals"],
                "outputs": ["notification_decision"],
                "control": {"gdpr": "Art.33", "statutory": True, "irreversible": True},
            },
            {
                "code": "A4",
                "what": "Record the decision and, where notified, the submission reference.",
                "responsible": "agent",
                "accountable_role": "DPO",
                "automation": "auto",
                "inputs": ["notification_decision"],
                "outputs": ["breach_evidence"],
                "control": {"gdpr": "Art.33"},
            },
        ],
    },
    {
        "wf_code": "WF-19",
        "name": "Business impact analysis and continuity planning",
        "family": "OPS",
        "pillars": ["bcp"],
        "tier": "L2",
        "owner_role": "Control Owner",
        "activities": [
            {
                "code": "A1",
                "what": "Identify the prioritised activity and its dependencies.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Draft the dependency map from the asset and supplier registers.",
                "task_class": "bia_drafting",
                "automation": "auto",
                "inputs": ["activity", "asset_register", "supplier_register"],
                "outputs": ["dependency_map"],
                "control": {"iso22301": "8.2.2"},
            },
            {
                "code": "A2",
                "what": "Analyse impact over time and propose MTPD, RTO and RPO.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Draft the impact profile and derive the recovery objectives.",
                "task_class": "bia_drafting",
                "automation": "auto",
                "inputs": ["dependency_map"],
                "outputs": ["impact_over_time", "rto", "rpo"],
                "control": {"iso22301": "8.2.2", "min_confidence": 0.75},
            },
            {
                "code": "A3",
                "what": "Approve the BIA and its recovery objectives.",
                "responsible": "human",
                "accountable_role": "Control Owner",
                "automation": "gate",
                "gate_type": "resilience.bia_signoff",
                "gate_reason": "high_risk",
                "inputs": ["impact_over_time", "rto", "rpo"],
                "outputs": ["approved_bia"],
                "control": {"iso22301": "8.2.2", "high_risk": True},
            },
            {
                "code": "A4",
                "what": "Draft the continuity strategy and plan against the approved objectives.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Draft strategy options that meet the RTO within known resources.",
                "task_class": "policy_drafting",
                "automation": "auto_notify",
                "inputs": ["approved_bia"],
                "outputs": ["continuity_plan"],
                "control": {"iso22301": "8.3.3"},
            },
        ],
    },
    {
        "wf_code": "WF-24",
        "name": "Supplier due diligence and engagement approval",
        "family": "TPRM",
        "pillars": ["security", "gdpr"],
        "tier": "L3",
        "owner_role": "Control Owner",
        "activities": [
            {
                "code": "A1",
                "what": "Tier the supplier by criticality and data access.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Propose the tier from the engagement description.",
                "task_class": "classification",
                "automation": "auto",
                "inputs": ["supplier", "engagement_scope"],
                "outputs": ["tier"],
            },
            {
                "code": "A2",
                "what": "Assess the supplier's responses across the security and privacy domains.",
                "responsible": "agent",
                "accountable_role": "Control Owner",
                "ai_role": "Score each domain and cite the response supporting the score.",
                "task_class": "supplier_assessment",
                "automation": "auto",
                "inputs": ["questionnaire_responses"],
                "outputs": ["domain_scores", "residual_rating"],
                "control": {"iso27001": "A.5.19", "min_confidence": 0.75},
            },
            {
                "code": "A3",
                "what": "Approve the engagement, with remediation conditions where needed.",
                "responsible": "human",
                "accountable_role": "Control Owner",
                "automation": "gate",
                "gate_type": "supplier.engagement",
                "gate_reason": "high_risk",
                "inputs": ["residual_rating"],
                "outputs": ["engagement_decision"],
                "control": {"iso27001": "A.5.19", "high_risk": True},
            },
        ],
    },
]
